### PR TITLE
Keybase patches + Updated README

### PR DESCRIPTION
**Pull request by lox**
In the spirit of getting upstream back to the canonical home for this package, this PR includes the changes that @akalin and @gabriel have made:
- Use generic keychain items rather than internet passwords
- Fix memory leaks and various bugs
- Simplify keychainError type
- Add a GetAllAccountNames() function

Thoughts on merging this in and then iterating somewhat on the API after some discussion?

### CODE REVIEW

**Comment by bgentry** [comment]
Thanks for putting this together. I will review it soon.

Looks like a small conflict (probably due to just-merged Solaris build
flag). Can you rebase on master and force push?

I'm more than willing to review and merge any PRs, including this one, but
I'm not sure it's ok to merge other authors' work into my license without
their express consent. @akalin @gabriel can you give some sort of
indication as to your stance on this?

**Comment by akalin-keybase** [comment]
This (and the MIT license) looks good to me!

**Comment by bgentry** [comment]
I've started looking at this, but it's impossible to merge in its current state due to conflicts. I'll need to spend some time reconciling that unless you can do so.

A couple of other things I noticed on the first pass:
- exported functions and constants no longer have documentation with this PR. To make the library follow Go best practices and be usable by e.g. godoc, it should follow standard conventions by documenting anything that's exported.
- should we really drop the InternetPassword functions as this PR does? Or should they be kept alongside the GenericPassword functions?

**Comment by lox** [comment]
Been thinking about this one a fair bit. Perhaps we should just iterate on #7 and come up with an API that works for both GenericPassword and InternetPassword?

Do you have a specific use for InternetPassword @bgentry?

**Comment by bgentry** [comment]
@lox I started using InternetPassword because it seemed simpler at the time (given how much I was struggling to get anything working here). I don't know whether I should just be using GenericPassword instead.

In general, I would prefer that this library map closely to the underlying API primitives in the Keychain Services APIs. We shouldn't try to offer a higher level abstraction that makes it harder to map from Keychain concepts and docs to this package. If there's a good opportunity to build such an abstraction to simplify usage for those who don't necessarily care about the underlying details, I'd prefer that be built alongside the basic building blocks or in another package.

I still think most of the stuff in here is good, though, and will spend some time trying to reconcile the two forks.

**Comment by akalin-keybase** [comment]
internet passwords are pretty different (have more options) from generic passwords, I think. If no one is actually using the internet password code, though, I'd prefer just ripping it out. We can always add it back later when it's needed!

I'll try and add docs for exported stuff (in the keybase fork).

**Comment by akalin-keybase** [comment]
Okay, added docs and fixed golint warnings.

**Comment by lox** [comment]
@akalin-keybase might be worth you opening a new PR directly from the keybase master?

**Pull request closed without merging**
